Pin 1318 [FILTER] BFF GET /agreements/consumers
pagopa/interop-be-agreement-process pull request #219
Opened 2023-02-15 10:02 UTC by nttdata-rtorsoli

[FILTER] BFF GET /agreements/consumers

2023-02-15 10:31 UTC, galales requested changes

2023-02-15 10:31 UTC, galales commented on src/main/resources/interface-specification.yml
> +                  $ref: '#/components/schemas/Problem'
this error should never occur (if no consumers have been found, an empty list is returned)

2023-02-15 10:31 UTC, galales commented on src/main/resources/interface-specification.yml
> +            description: Query to filter EServices by name
```suggestion
            name: consumerName
            description: Query to filter Consumers by name
```

2023-02-15 10:31 UTC, galales commented on src/main/scala/it/pagopa/interop/agreementprocess/common/readmodel/ReadModelQueries.scala
> +    val query: Bson               = listEServiceFilters(name)
this filter should be by consumer name, not eservice name

2023-02-16 07:52 UTC, galales approved these changes

2023-02-16 16:00 UTC, TonioGela approved these changes

2023-02-20 13:57 UTC, merged