PIN-3492
pagopa/interop-be-agreement-process pull request #234
Opened 2023-06-29 07:57 UTC by nttdata-rtorsoli

2023-06-29 08:33 UTC, TonioGela commented on src/main/scala/it/pagopa/interop/agreementprocess/api/impl/AgreementApiServiceImpl.scala
> +     */
🧹

2023-06-29 08:35 UTC, TonioGela commented on src/main/scala/it/pagopa/interop/agreementprocess/api/impl/AgreementApiServiceImpl.scala
> +      )
```suggestion
      eServices <- uniqueEServiceIds.traverse(catalogManagementService.getEServiceById)
```

2023-07-04 12:18 UTC, galales approved these changes
Overall LGTM, just some minor considerations

2023-07-04 12:18 UTC, galales commented on lifecycle/src/test/scala/it/pagopa/interop/agreementprocess/lifecycle/AttributesRulesSpec.scala
> +    "return true if all CatalogItem single attributes are satisfied" in {
You can leave `EService` as conceptual model here. `CatalogItem` is a legacy name.
Same for all other test descriptions in this file.

```suggestion
    "return true if all EService single attributes are satisfied" in {
```

2023-07-04 12:18 UTC, galales commented on project/Dependencies.scala
>      lazy val tenantManagementClient = namespace %% "interop-be-tenant-management-client"   % tenantManagementVersion
🧹 
```suggestion
```

2023-07-04 12:18 UTC, galales commented on src/main/scala/it/pagopa/interop/agreementprocess/api/impl/AgreementApiServiceImpl.scala
> +        .getEServiceById(payload.eserviceId)
to reduce noice, can you make this and all other similar changes in one line?
```suggestion
      eService       <- catalogManagementService.getEServiceById(payload.eserviceId)
```

2023-07-04 12:18 UTC, galales commented on src/main/scala/it/pagopa/interop/agreementprocess/api/impl/AgreementApiServiceImpl.scala
> +        )
Very very minor code improvement
```suggestion
        .flatMap {
          case single: SingleAttribute => Seq(single.id.id)
          case group: GroupAttribute   => group.ids.map(_.id)
        }
```

2023-07-04 12:18 UTC, galales commented on src/main/scala/it/pagopa/interop/agreementprocess/api/impl/AgreementApiServiceImpl.scala
> +      )
```suggestion
      .flatMap {
          case single: SingleAttribute => Seq(single.id.id)
          case group: GroupAttribute   => group.ids.map(_.id)
        }
```

2023-07-04 12:18 UTC, galales commented on src/main/scala/it/pagopa/interop/agreementprocess/common/Adapters.scala
> -
do not move code please 🙏

2023-07-04 12:18 UTC, galales commented on src/main/scala/it/pagopa/interop/agreementprocess/common/Adapters.scala
> +    )
do not move code please 🙏

2023-07-04 12:18 UTC, galales commented on src/main/scala/it/pagopa/interop/agreementprocess/common/Adapters.scala
> +    def toSeed(newId: UUID, newPath: String): AgreementManagement.DocumentSeed = AgreementManagement.DocumentSeed(
do not move code please 🙏

2023-07-04 12:41 UTC, TonioGela requested changes
Overall looks good, but there are many places where newlines are not needed

2023-07-04 13:21 UTC, beetlecrunch approved these changes

2023-07-05 11:36 UTC, nttdata-rtorsoli commented on src/main/scala/it/pagopa/interop/agreementprocess/common/Adapters.scala
> +    def toSeed(newId: UUID, newPath: String): AgreementManagement.DocumentSeed = AgreementManagement.DocumentSeed(
I am obliged to move code because wrapper type is different

2023-07-05 11:36 UTC, nttdata-rtorsoli commented on src/main/scala/it/pagopa/interop/agreementprocess/common/Adapters.scala
> +    )
I am obliged to move code because wrapper type is different

2023-07-05 11:36 UTC, nttdata-rtorsoli commented on src/main/scala/it/pagopa/interop/agreementprocess/common/Adapters.scala
> -
I am obliged to move code because wrapper type is different

2023-07-05 12:15 UTC, galales approved these changes
approving in advance, but not all occurrences of the comments have been addressed

2023-07-06 07:58 UTC, galales commented on src/main/scala/it/pagopa/interop/agreementprocess/common/Adapters.scala
>      Set(Draft, MissingCertifiedAttributes)
the duplication of these states can be problematic during the maintenance.
If one of the two sets is no more used, feel free to remove it (I suggest to leave the old names though)

2023-07-06 07:58 UTC, galales commented on src/main/scala/it/pagopa/interop/agreementprocess/common/Adapters.scala
>    implicit class AgreementWrapper(private val a: AgreementManagement.Agreement) extends AnyVal {
same for the states, if these are no more used 🔥

2023-07-06 09:01 UTC, TonioGela approved these changes

2023-07-06 12:28 UTC, galales approved these changes

2023-07-06 14:29 UTC, merged