PIN-3590 Archive endpoint
pagopa/interop-be-agreement-process pull request #238
Opened 2023-07-05 08:12 UTC by nttdata-rtorsoli

2023-07-05 12:38 UTC, beetlecrunch commented on src/main/resources/application.conf
> +  events-queue-name         = ${EVENTS_QUEUE_NAME}
```suggestion
  archiving-purposes-queue-name         = ${ARCHIVING_PURPOSES_QUEUE_NAME}
```
Probably this service will push the same event twice into another queue (I'm talking about the eservice version archiving feature).
So may I suggest renaming like above?

2023-07-05 12:38 UTC, beetlecrunch commented on src/main/resources/application-standalone.conf
> +  events-queue-name         = ${EVENTS_QUEUE_NAME}
[same](https://github.com/pagopa/interop-be-agreement-process/pull/238/files#r1253046683)

2023-07-05 12:40 UTC, TonioGela approved these changes

2023-07-05 12:40 UTC, beetlecrunch commented on src/main/scala/it/pagopa/interop/agreementprocess/api/impl/AgreementApiServiceImpl.scala
> +  queueEventsService: QueueService
```suggestion
  certifiedMailQueueService: QueueService,
  archivingPurposesQueueService: QueueService
```

2023-07-05 12:42 UTC, beetlecrunch commented on src/main/scala/it/pagopa/interop/agreementprocess/common/system/ApplicationConfiguration.scala
> +  val eventsQueueName: String          = config.getString("agreement-process.events-queue-name")
[same](https://github.com/pagopa/interop-be-agreement-process/pull/238/files#r1253046683) considarations

2023-07-05 12:44 UTC, beetlecrunch commented on src/test/resources/application-test.conf
> +  events-queue-name         = "events-queue-name"
[same](https://github.com/pagopa/interop-be-agreement-process/pull/238/files#r1253046683)

2023-07-06 06:37 UTC, beetlecrunch approved these changes

2023-07-06 09:22 UTC, galales requested changes
Minor point on dependencies.
Fixed required on authorization

2023-07-06 09:22 UTC, galales commented on events/src/main/scala/it/interop/agreementprocess/events/Events.scala
> +import akka.http.scaladsl.marshallers.sprayjson.SprayJsonSupport
is `akka` required in this case? is `spary` enough?

2023-07-06 09:22 UTC, galales commented on project/Dependencies.scala
> +        akka.httpJson                    % Compile,
same for `spray`

2023-07-06 09:22 UTC, galales commented on src/main/scala/it/pagopa/interop/agreementprocess/api/impl/AgreementApiServiceImpl.scala
> +      _              <- assertRequesterIsProducer(requesterOrgId, agreement)
As per story description
```suggestion
      _              <- assertRequesterIsConsumer(requesterOrgId, agreement)
```

2023-07-06 12:29 UTC, galales approved these changes

2023-07-06 16:25 UTC, merged