PIN-3142 Make it mandatory to enter the email when forwarding a request
pagopa/interop-be-agreement-process pull request #243
Opened 2023-07-24 11:05 UTC by nttdata-rtorsoli

2023-07-26 08:18 UTC, TonioGela requested changes

2023-07-26 08:18 UTC, TonioGela commented on src/main/scala/it/pagopa/interop/agreementprocess/api/impl/AgreementApiServiceImpl.scala
> +          .whenA(consumer.mails.filter(_.kind == PersistentTenantMailKind.ContactEmail).isEmpty)
don't use cats with future
```suggestion
        _        <- if (consumer.mails.filter(_.kind == PersistentTenantMailKind.ContactEmail).isEmpty) 
        Future.failed(ConsumerWithNotValidEmail(agreement.id, agreement.consumerId))
        else Future.unit
```

2023-07-26 09:03 UTC, TonioGela approved these changes

2023-07-26 12:57 UTC, galales requested changes

2023-07-26 12:57 UTC, galales commented on src/main/scala/it/pagopa/interop/agreementprocess/api/impl/AgreementApiServiceImpl.scala
> +      _      <- if (agreement.state == Draft && newState == Pending) validateConsumerEmails(agreement) else Future.unit
Agreement submission can also directly pass from Draft to Active
```suggestion
      _      <- if (agreement.state == Draft) validateConsumerEmails(agreement) else Future.unit
```

2023-07-26 12:57 UTC, galales commented on src/main/scala/it/pagopa/interop/agreementprocess/api/impl/AgreementApiServiceImpl.scala
> +          if (consumer.mails.filter(_.kind == PersistentTenantMailKind.ContactEmail).isEmpty)
```suggestion
          if (!consumer.mails.exists(_.kind == PersistentTenantMailKind.ContactEmail))
```

2023-07-26 12:57 UTC, galales commented on src/main/scala/it/pagopa/interop/agreementprocess/error/AgreementProcessErrors.scala
> +  case object InvalidAttributeStructure extends ComponentError("0024", "Invalid Attribute Structure")
we should avoid to change error codes if not strictly required
```suggestion
  case object InvalidAttributeStructure extends ComponentError("0023", "Invalid Attribute Structure")
```

2023-07-26 12:57 UTC, galales commented on src/main/scala/it/pagopa/interop/agreementprocess/error/AgreementProcessErrors.scala
> +        "0023",
```suggestion
        "0024",
```

2023-07-27 08:20 UTC, galales approved these changes

2023-08-07 07:58 UTC, merged