PIN-4903 BKE - Error during selfcare information retrieve at the creation of agreement contract
pagopa/interop-be-agreement-process pull request #263
Opened 2024-05-16 13:03 UTC by nttdata-rtorsoli

2024-05-28 14:07 UTC, galales requested changes
reminder: check tests

2024-05-28 14:07 UTC, galales commented on src/main/scala/it/pagopa/interop/agreementprocess/service/AgreementContractCreator.scala
> +        .getUserById(consumerSelfcareUuid, consumerApi.id)
the `consumerApi.id` is exactly the `consumerSelfcareId`, no need to retrieve it again.
Same for `producerApi.id`.

Plus, the second parameter of `getUserById` should be a user id, but here we are passing an institution if

2024-05-28 14:07 UTC, galales commented on src/main/scala/it/pagopa/interop/agreementprocess/service/AgreementContractCreator.scala
> +        .getUserById(consumerSelfcareUuid, consumerApi.id)
I updated the ticket, the submission can be performed only by the consumer, it is enough to retrieve from selfcare the user info always in relation to the consumer

2024-05-28 15:02 UTC, nttdata-rtorsoli commented on src/main/scala/it/pagopa/interop/agreementprocess/service/AgreementContractCreator.scala
> +        .getUserById(consumerSelfcareUuid, consumerApi.id)
Where I can retrieve userId for consumer?

2024-05-30 07:24 UTC, galales commented on src/main/scala/it/pagopa/interop/agreementprocess/service/AgreementContractCreator.scala
> +        .getUserById(consumerSelfcareUuid, consumerApi.id)
the userId is the `who` field in the stamp

2024-05-30 08:48 UTC, beetlecrunch approved these changes

2024-05-30 09:56 UTC, galales approved these changes

2024-05-30 13:53 UTC, merged